import FavoriteImage from "../../../assets/images/FavoriteImage.png";


export const contactsData = [
  {
    id: 1,
    name: "Regina Cooper",
    designation: "Manager",
    location: "Sochi, Russia",
    email: "cooper@example.com",
    phone: "+1 (070) 123-4567",
    avatar: FavoriteImage,
  },
  {
    id: 2,
    name: "Judith Black",
    designation: "Creative Director",
    location: "New York, USA",
    email: "black@example.com",
    phone: "+1 (070) 123-8459",
    avatar: FavoriteImage,
  },
  {
    id: 3,
    name: "Ronald Robertson",
    designation: "Manager",
    location: "Paris, France",
    email: "robe@example.com",
    phone: "+1 (070) 123-9221",
    avatar: FavoriteImage,
  },
  {
    id: 4,
    name: "Dustin Williamson",
    designation: "Designer",
    location: "Sydney, Australia",
    email: "williams@example.com",
    phone: "+1 (070) 123-0507",
    avatar: FavoriteImage,
  },
  {
    id: 5,
    name: "Calvin Flores",
    designation: "Manager",
    location: "Berlin, Germany",
    email: "flores@example.com",
    phone: "+1 (070) 123-4567",
    avatar: FavoriteImage,
  },
  {
    id: 6,
    name: "Robert Edwards",
    designation: "Developer",
    location: "Shanghai, China",
    email: "edwards@example.com",
    phone: "+1 (070) 123-1477",
    avatar: FavoriteImage,
  },
  {
    id: 7,
    name: "Colleen Warren",
    designation: "Manager",
    location: "London, UK",
    email: "warren@example.com",
    phone: "+1 (070) 123-9127",
    avatar: FavoriteImage,
  },
  {
    id: 8,
    name: "Bessie Henry",
    designation: "Designer",
    location: "New York, USA",
    email: "henry@example.com",
    phone: "+1 (070) 123-4567",
    avatar: FavoriteImage,
  },
];