const ordersData = [
  {
    id: 1,
    orderNo: "#790841",
    customer: "Claire Warren",
    date: "12.09.20",
    total: "$145.85",
    payment: "PayPal",
    status: "Shipped",
    selected: false,
  },
  {
    id: 2,
    orderNo: "#790841",
    customer: "Theresa Robertson",
    date: "12.09.20",
    total: "$225.15",
    payment: "Credit Card",
    status: "Shipped",
    selected: true,
  },
  {
    id: 3,
    orderNo: "#790841",
    customer: "Nathan Hawkins",
    date: "12.09.20",
    total: "$45.55",
    payment: "PayPal",
    status: "Shipped",
    selected: true,
  },
  {
    id: 4,
    orderNo: "#790841",
    customer: "Lily Williamson",
    date: "12.09.20",
    total: "$305.25",
    payment: "Credit Card",
    status: "Processing",
    selected: true,
  },
  {
    id: 5,
    orderNo: "#790841",
    customer: "Brooklyn Steward",
    date: "12.09.20",
    total: "$483.80",
    payment: "Credit Card",
    status: "Shipped",
    selected: false,
  },
  {
    id: 6,
    orderNo: "#790841",
    customer: "Norma Flores",
    date: "12.09.20",
    total: "$128.79",
    payment: "Payoneer",
    status: "Processing",
    selected: false,
  },
  {
    id: 7,
    orderNo: "#790841",
    customer: "Leslie Mckinney",
    date: "12.09.20",
    total: "$105.05",
    payment: "Credit Card",
    status: "Cancelled",
    selected: false,
  },
  {
    id: 8,
    orderNo: "#790841",
    customer: "Gregory Black",
    date: "12.09.20",
    total: "$1028.15",
    payment: "PayPal",
    status: "Shipped",
    selected: false,
  },
];

export default ordersData;