import avatar from "../../../../../assets/images/FavoriteImage.png";

export const contactsListViewData = [
  {
    id: 1,
    name: "Regina Cooper",
    designation: "Manager",
    location: "Sochi, Russia",
    email: "cooper@example.com",
    phone: "+1 (070) 123-4567",
    image: avatar,
  },
  {
    id: 2,
    name: "Judith Black",
    designation: "Creative Director",
    location: "New York, USA",
    email: "black@example.com",
    phone: "+1 (070) 123-8459",
    image: avatar,
  },
  {
    id: 3,
    name: "Ronald Robertson",
    designation: "Manager",
    location: "Paris, France",
    email: "robe@example.com",
    phone: "+1 (070) 123-9221",
    image: avatar,
  },
  {
    id: 4,
    name: "Dustin Williamson",
    designation: "Designer",
    location: "Sydney, Australia",
    email: "williams@example.com",
    phone: "+1 (070) 123-4567",
    image: avatar,
  },
  {
    id: 5,
    name: "Calvin Flores",
    designation: "Manager",
    location: "Berlin, Germany",
    email: "flores@example.com",
    phone: "+1 (070) 123-3791",
    image: avatar,
  },
  {
    id: 6,
    name: "Robert Edwards",
    designation: "Developer",
    location: "Shanghai, China",
    email: "edwards@example.com",
    phone: "+1 (070) 123-1147",
    image: avatar,
  },
  {
    id: 7,
    name: "Nathan Fox",
    designation: "Designer",
    location: "London, UK",
    email: "fox@example.com",
    phone: "+1 (070) 123-5073",
    image: avatar,
  },
  {
    id: 8,
    name: "Colleen Warren",
    designation: "Manager",
    location: "Ottawa, Canada",
    email: "warren@example.com",
    phone: "+1 (070) 123-9127",
    image: avatar,
  },
  {
    id: 9,
    name: "Bessie Henry",
    designation: "Developer",
    location: "New York, USA",
    email: "henry@example.com",
    phone: "+1 (070) 123-3578",
    image: avatar,
  },
  {
    id: 10,
    name: "Philip Mccoy",
    designation: "Developer",
    location: "Sydney, Australia",
    email: "mccoy@example.com",
    phone: "+1 (070) 123-4588",
    image: avatar,
  },
  {
    id: 11,
    name: "Dustin Lane",
    designation: "Manager",
    location: "Los Angeles, USA",
    email: "lane@example.com",
    phone: "+1 (070) 123-0215",
    image: avatar,
  },
  {
    id: 12,
    name: "Shane Black",
    designation: "Manager",
    location: "Oslo, Norway",
    email: "black@example.com",
    phone: "+1 (070) 123-8896",
    image: avatar,
  },
];