import picture from "../../../assets/images/picture.png"

export const productDataGrid = [
  {
    id: 1,
    checked: false,
    image: picture,
    productName: "Apple iPhone 11 Pro Max 256GB Space Gray",
    status: "Available",
    category: "Phone",
    date: "12.09.20",
    price: "$2,500",
  },
  {
    id: 2,
    checked: false,
    image: picture,
    productName: "Apple Watch Series 5 Edition GPS + Cellular",
    status: "Available",
    category: "Watch",
    date: "12.09.20",
    price: "$2,500",
  },
  {
    id: 3,
    checked: false,
    image: picture,
    productName: "Apple iPhone 11 Pro Max 256GB Space Gray",
    status: "Disabled",
    category: "Phone",
    date: "12.09.20",
    price: "$2,500",
  },
  {
    id: 4,
    checked: false,
    image: picture,
    productName: "Apple Watch Series 5 Edition GPS + Cellular",
    status: "Disabled",
    category: "Watch",
    date: "12.09.20",
    price: "$2,500",
  },
  {
    id: 5,
    checked: false,
    image: picture,
    productName: "Apple iPhone 11 Pro Max 256GB Space Gray",
    status: "Available",
    category: "Phone",
    date: "12.09.20",
    price: "$2,500",
  },
    {
    id: 6,
    checked: false,
    image: picture,
    productName: "Apple iPhone 11 Pro Max 256GB Space Gray",
    status: "Available",
    category: "Phone",
    date: "12.09.20",
    price: "$2,500",
  },
    {
    id: 6,
    checked: true,
    image: picture,
    productName: "Apple iPhone 11 Pro Max 256GB Space Gray",
    status: "Available",
    category: "Phone",
    date: "12.09.20",
    price: "$2,500",
  },
    {
    id: 7,
    checked: false,
    image: picture,
    productName: "Apple iPhone 11 Pro Max 256GB Space Gray",
    status: "Available",
    category: "Phone",
    date: "12.09.20",
    price: "$2,500",
  },
];