import FavoriteImage from "../../../assets/images/FavoriteImage.png";

import DropboxOne from "../../../assets/images/DropboxOne.png";
import DropboxTwo from "../../../assets/images/DropboxTwo.png";
import DropboxThree from "../../../assets/images/DropboxThree.png";
import DropboxFour from "../../../assets/images/DropboxFour.png";
import DropboxFive from "../../../assets/images/DropboxFive.png";
import DropboxSix from "../../../assets/images/DropboxSix.png";
import DropboxSeven from "../../../assets/images/DropboxSeven.png";
import DropboxEight from "../../../assets/images/DropboxEight.png";
import DropboxNine from "../../../assets/images/DropboxNine.png";
import java from "../../../assets/images/java.png";

export const projectListData = [
  {
    id: 1,
    logo: DropboxOne,
    projectName: "App Development",
    company: "Dropbox, Inc.",
    manager: "Shane Black",
    designation: "Project Manager",
    avatar: FavoriteImage,
    progress: 50,
    deadline: "1 week left",
    deadlineColor: "default",
  },
  {
    id: 2,
    logo: DropboxTwo,
    projectName: "Website Redesign",
    company: "GitLab Inc.",
    manager: "Jane Wilson",
    designation: "Project Manager",
    avatar: FavoriteImage,
    progress: 75,
    deadline: "1 week left",
    deadlineColor: "default",
  },
  {
    id: 3,
    logo: DropboxThree,
    projectName: "Landing Page",
    company: "Bitbucket, Inc.",
    manager: "Shane Black",
    designation: "Project Manager",
    avatar: FavoriteImage,
    progress: 100,
    deadline: "1 week left",
    deadlineColor: "default",
  },
  {
    id: 4,
    logo: DropboxFour,
    projectName: "Parser Development",
    company: "Driveway, Inc.",
    manager: "Jacob Hawkins",
    designation: "Project Manager",
    avatar: FavoriteImage,
    progress: 50,
    deadline: "5 days left",
    deadlineColor: "warning",
  },
  {
    id: 5,
    logo: DropboxFive,
    projectName: "App Development",
    company: "Slack Technologies, Inc.",
    manager: "Jacob Hawkins",
    designation: "Project Manager",
    avatar: FavoriteImage,
    progress: 50,
    deadline: "5 days left",
    deadlineColor: "warning",
  },
  {
    id: 6,
    logo: DropboxSix,
    projectName: "App Development",
    company: "Google, Inc.",
    manager: "Ronald Robertson",
    designation: "Project Manager",
    avatar: FavoriteImage,
    progress: 25,
    deadline: "1 week left",
    deadlineColor: "default",
  },
  {
    id: 7,
    logo: DropboxSeven,
    projectName: "Admin Dashboard",
    company: "ArtTemplate, Inc.",
    manager: "Shane Black",
    designation: "Project Manager",
    avatar: FavoriteImage,
    progress: 30,
    deadline: "1 week left",
    deadlineColor: "default",
  },
  {
    id: 8,
    logo: DropboxEight,
    projectName: "Web App on Vue.js",
    company: "ArtTemplate, Inc.",
    manager: "Robert Edwards",
    designation: "Project Manager",
    avatar: FavoriteImage,
    progress: 100,
    deadline: "1 week left",
    deadlineColor: "default",
  },
  {
    id: 9,
    logo: DropboxNine,
    projectName: "App Development",
    company: "Facebook, Inc.",
    manager: "Ronald Robertson",
    designation: "Project Manager",
    avatar: FavoriteImage,
    progress: 50,
    deadline: "1 week left",
    deadlineColor: "default",
  },
  {
    id: 10,
    logo: java,
    projectName: "App Development",
    company: "Leader, Inc.",
    manager: "Shane Black",
    designation: "Project Manager",
    avatar: FavoriteImage,
    progress: 75,
    deadline: "1 week left",
    deadlineColor: "default",
  },
];