import ProfileDash from "../../assets/images/ProfileDash.png";

export const contacts = [
  {
    id: 1,
    avatar: ProfileDash,
    name: "Regina Cooper",
    role: "Manager",
    email: "cooper@example.com",
    location: "Sochi, Russia",
    phone: "+1 (070) 123-4567",
    status: "Active",
    birthday: "17 March, 1995",
  },
  {
    id: 2,
    avatar: ProfileDash,
    name: "Judith Black",
    role: "Creative Director",
    email: "black@example.com",
    location: "New York, USA",
    phone: "+1 (070) 123-8459",
    status: "Active",
    birthday: "12 April, 1994",
  },
  {
    id: 3,
    avatar: ProfileDash,
    name: "Ronald Robertson",
    role: "Product Designer",
    email: "ronald@example.com",
    location: "London, UK",
    phone: "+44 7012 345678",
    status: "Active",
    birthday: "20 June, 1992",
  },
  {
    id: 4,
    avatar: ProfileDash,
    name: "Jenny Wilson",
    role: "UI Designer",
    email: "jenny@example.com",
    location: "Toronto, Canada",
    phone: "+1 416 123 4567",
    status: "Active",
    birthday: "08 August, 1997",
  },
  {
    id: 5,
    avatar: ProfileDash,
    name: "Esther Howard",
    role: "HR Manager",
    email: "esther@example.com",
    location: "Berlin, Germany",
    phone: "+49 170 4567890",
    status: "Active",
    birthday: "30 January, 1990",
  },
  {
    id: 6,
    avatar: ProfileDash,
    name: "Cody Fisher",
    role: "Backend Developer",
    email: "cody@example.com",
    location: "Sydney, Australia",
    phone: "+61 456 123 456",
    status: "Active",
    birthday: "11 September, 1991",
  },
  {
    id: 7,
    avatar: ProfileDash,
    name: "Jacob Jones",
    role: "Frontend Developer",
    email: "jacob@example.com",
    location: "Dubai, UAE",
    phone: "+971 50 123 4567",
    status: "Active",
    birthday: "15 December, 1993",
  },
  {
    id: 8,
    avatar: ProfileDash,
    name: "Savannah Nguyen",
    role: "QA Engineer",
    email: "savannah@example.com",
    location: "Singapore",
    phone: "+65 8123 4567",
    status: "Active",
    birthday: "10 February, 1996",
  },
  {
    id: 9,
    avatar: ProfileDash,
    name: "Brooklyn Simmons",
    role: "Business Analyst",
    email: "brooklyn@example.com",
    location: "Paris, France",
    phone: "+33 612 345678",
    status: "Active",
    birthday: "27 July, 1992",
  },
  {
    id: 10,
    avatar: ProfileDash,
    name: "Kathryn Murphy",
    role: "Marketing Lead",
    email: "kathryn@example.com",
    location: "Amsterdam, Netherlands",
    phone: "+31 612345678",
    status: "Active",
    birthday: "03 November, 1994",
  },
];
